-- =========================================
-- Project: ABC Events SQL Project
-- File: 01_create_tables.sql
-- Purpose: Create all tables (1–22)
-- =========================================

-- 1. THEME
CREATE TABLE THEME (
    TYPE VARCHAR(50)
);

-- 2. VENUE
CREATE TABLE VENUE (
    VENUE_NAME VARCHAR(100),
    LOCATION VARCHAR(150)
);

-- 3. EQUIPMENTS
CREATE TABLE EQUIPMENTS (
    CATEGORY VARCHAR(100),
    STORAGE_LOCATION VARCHAR(150)
);

-- 4. CLIENT
CREATE TABLE CLIENT (
    CLIENT_NAME VARCHAR(100),
    CLIENT_PHONE VARCHAR(25),
    CLIENT_EMAIL VARCHAR(120),
    PREFERENCE VARCHAR(200)
);

-- 5. EVENT
CREATE TABLE EVENT (
    DATE DATE,
    TIME TIME
);

-- 6. VENDOR
CREATE TABLE VENDOR (
    VENDOR_TYPE VARCHAR(80)
);

-- 7. INVOICES
CREATE TABLE INVOICES (
    ISSUE_DATE DATE,
    AMOUNT FLOAT,
    CLIENT_NAME VARCHAR(100)
);

-- 8. PAYMENT
CREATE TABLE PAYMENT (
    PAYMENT_DATE DATE,
    PAYMENT_TYPE VARCHAR(40),
    BALANCE_DUE FLOAT
);

-- 9. STAFF
CREATE TABLE STAFF (
    F_NAME VARCHAR(50),
    L_NAME VARCHAR(50),
    DESIGNATION VARCHAR(60)
);

-- 10. PERFORMERS
CREATE TABLE PERFORMERS (
    ARTIST_NAME VARCHAR(120),
    PERFORMANCE_TYPE VARCHAR(80)
);

-- 11. SCHEDULE
CREATE TABLE SCHEDULE (
    ACTIVITY VARCHAR(100),
    ASSIGNED_STAFF VARCHAR(50),
    DURATION INT
);

-- 12. ATTENDEES
CREATE TABLE ATTENDEES (
    ATTENDEE_PHONE INT,
    ATTENDEE_EMAIL VARCHAR(80),
    RSVP_NUMBER INT
);

-- 13. EVENT_PLANNER
CREATE TABLE EVENT_PLANNER (
    EVENTPLANNERID VARCHAR(20),
    EVENTPLANNER_NAME VARCHAR(20),
    LICENSE_ID VARCHAR(20)
);

-- 14. EVENT_STAFF
CREATE TABLE EVENT_STAFF (
    DEPARTMENT VARCHAR(50) NOT NULL,
    ROLE_TYPE VARCHAR(50)
);

-- 15. VENUE_EQUIPMENTS
CREATE TABLE VENUE_EQUIPMENTS (
    VENUEID VARCHAR(30) NOT NULL
);

-- 16. SCHEDULE_EVENT
CREATE TABLE SCHEDULE_EVENT (
    ACTIVITY VARCHAR(100),
    ASSIGNED_STAFF VARCHAR(50),
    DURATION INT,
    TIME TIME,
    DATE DATE,
    EVENT_ID VARCHAR(20)
);

-- 17. EVENT_INVOICES
CREATE TABLE EVENT_INVOICES (
    DATE DATE,
    TIME TIME,
    INVOICEID VARCHAR(20),
    ISSUE_DATE DATE,
    AMOUNT INT
);

-- 18. SCHEDULE_PERFORMERS
CREATE TABLE SCHEDULE_PERFORMERS (
    SCHEDULEID VARCHAR(20) NOT NULL
);

-- 19. VENDORS_EVENT
CREATE TABLE VENDORS_EVENT (
    VENDORID VARCHAR(20) NOT NULL
);

-- 20. ATTENDEE_EVENT
CREATE TABLE ATTENDEE_EVENT (
    ATTENDEE_NAME VARCHAR(80) NOT NULL
);

-- 21. STAFF_EVENT
CREATE TABLE STAFF_EVENT (
    STAFFID VARCHAR(20) NOT NULL
);

-- 22. STAFF_SUPERVISOR
CREATE TABLE STAFF_SUPERVISOR (
    STAFFID VARCHAR(20) NOT NULL
);
