-- =========================================
-- 02_alter_tables.sql
-- Adds PK/FK columns + constraints (MySQL)
-- =========================================

/* 1) THEME */
ALTER TABLE THEME ADD COLUMN themeID VARCHAR(20);
ALTER TABLE THEME MODIFY themeID VARCHAR(20) NOT NULL FIRST;
ALTER TABLE THEME ADD CONSTRAINT pk_theme PRIMARY KEY (themeID);

/* 2) VENUE */
ALTER TABLE VENUE ADD COLUMN venueID VARCHAR(20);
ALTER TABLE VENUE MODIFY venueID VARCHAR(20) NOT NULL FIRST;
ALTER TABLE VENUE ADD CONSTRAINT pk_venue PRIMARY KEY (venueID);

/* 3) VENDOR */
ALTER TABLE VENDOR ADD COLUMN vendorID VARCHAR(20);
ALTER TABLE VENDOR MODIFY vendorID VARCHAR(20) NOT NULL FIRST;
ALTER TABLE VENDOR ADD CONSTRAINT pk_vendor PRIMARY KEY (vendorID);

/* 4) SCHEDULE */
ALTER TABLE SCHEDULE ADD COLUMN scheduleID VARCHAR(20);
ALTER TABLE SCHEDULE MODIFY scheduleID VARCHAR(20) NOT NULL FIRST;
ALTER TABLE SCHEDULE ADD CONSTRAINT pk_schedule PRIMARY KEY (scheduleID);

/* 5) ATTENDEES
   You were using name in inserts, so we add it and use it as PK.
   (Phone should be BIGINT, not INT, for safety.)
*/
ALTER TABLE ATTENDEES ADD COLUMN attendee_name VARCHAR(80);
ALTER TABLE ATTENDEES MODIFY attendee_name VARCHAR(80) NOT NULL FIRST;
ALTER TABLE ATTENDEES MODIFY ATTENDEE_PHONE BIGINT;
ALTER TABLE ATTENDEES ADD CONSTRAINT pk_attendees PRIMARY KEY (attendee_name);

/* 6) STAFF */
ALTER TABLE STAFF ADD COLUMN staffID VARCHAR(20);
ALTER TABLE STAFF MODIFY staffID VARCHAR(20) NOT NULL FIRST;
ALTER TABLE STAFF ADD CONSTRAINT pk_staff PRIMARY KEY (staffID);

/* 7) EVENT_STAFF */
ALTER TABLE EVENT_STAFF ADD COLUMN staffID VARCHAR(20);
ALTER TABLE EVENT_STAFF MODIFY staffID VARCHAR(20) NOT NULL FIRST;
ALTER TABLE EVENT_STAFF ADD CONSTRAINT pk_event_staff PRIMARY KEY (staffID);

/* 8) EVENT_PLANNER */
ALTER TABLE EVENT_PLANNER ADD COLUMN staffID VARCHAR(20);
ALTER TABLE EVENT_PLANNER MODIFY staffID VARCHAR(20) NOT NULL FIRST;
ALTER TABLE EVENT_PLANNER ADD CONSTRAINT pk_event_planner PRIMARY KEY (staffID);

/* 9) INVOICES */
ALTER TABLE INVOICES ADD COLUMN invoiceID VARCHAR(20);
ALTER TABLE INVOICES MODIFY invoiceID VARCHAR(20) NOT NULL FIRST;
ALTER TABLE INVOICES ADD CONSTRAINT pk_invoices PRIMARY KEY (invoiceID);

/* 10) PAYMENT (needs invoiceID FK) */
ALTER TABLE PAYMENT ADD COLUMN paymentID VARCHAR(20);
ALTER TABLE PAYMENT ADD COLUMN invoiceID VARCHAR(20);
ALTER TABLE PAYMENT MODIFY paymentID VARCHAR(20) NOT NULL FIRST;
ALTER TABLE PAYMENT ADD CONSTRAINT pk_payment PRIMARY KEY (paymentID);
ALTER TABLE PAYMENT ADD CONSTRAINT fk_payment_invoice
  FOREIGN KEY (invoiceID) REFERENCES INVOICES(invoiceID);

/* 11) PERFORMERS */
ALTER TABLE PERFORMERS ADD COLUMN performerID VARCHAR(20);
ALTER TABLE PERFORMERS MODIFY performerID VARCHAR(20) NOT NULL FIRST;
ALTER TABLE PERFORMERS ADD CONSTRAINT pk_performers PRIMARY KEY (performerID);

/* 12) CLIENT */
ALTER TABLE CLIENT ADD COLUMN clientID VARCHAR(20);
ALTER TABLE CLIENT MODIFY clientID VARCHAR(20) NOT NULL FIRST;
ALTER TABLE CLIENT ADD CONSTRAINT pk_client PRIMARY KEY (clientID);

/* 13) EQUIPMENTS */
ALTER TABLE EQUIPMENTS ADD COLUMN equipment_num VARCHAR(20);
ALTER TABLE EQUIPMENTS MODIFY equipment_num VARCHAR(20) NOT NULL FIRST;
ALTER TABLE EQUIPMENTS ADD CONSTRAINT pk_equipments PRIMARY KEY (equipment_num);

/* 14) EVENT (add PK + FKs) */
ALTER TABLE EVENT ADD COLUMN eventID VARCHAR(20);
ALTER TABLE EVENT ADD COLUMN themeID VARCHAR(20);
ALTER TABLE EVENT ADD COLUMN venueID VARCHAR(20);
ALTER TABLE EVENT ADD COLUMN clientID VARCHAR(20);
ALTER TABLE EVENT MODIFY eventID VARCHAR(20) NOT NULL FIRST;

ALTER TABLE EVENT ADD CONSTRAINT pk_event PRIMARY KEY (eventID);
ALTER TABLE EVENT ADD CONSTRAINT fk_event_theme  FOREIGN KEY (themeID) REFERENCES THEME(themeID);
ALTER TABLE EVENT ADD CONSTRAINT fk_event_venue  FOREIGN KEY (venueID) REFERENCES VENUE(venueID);
ALTER TABLE EVENT ADD CONSTRAINT fk_event_client FOREIGN KEY (clientID) REFERENCES CLIENT(clientID);

/* 15) VENUE_EQUIPMENTS (junction table needs BOTH columns + composite PK) */
ALTER TABLE VENUE_EQUIPMENTS ADD COLUMN equipment_num VARCHAR(20);

ALTER TABLE VENUE_EQUIPMENTS ADD CONSTRAINT fk_ve_venue
  FOREIGN KEY (VENUEID) REFERENCES VENUE(venueID);

ALTER TABLE VENUE_EQUIPMENTS ADD CONSTRAINT fk_ve_equipment
  FOREIGN KEY (equipment_num) REFERENCES EQUIPMENTS(equipment_num);

ALTER TABLE VENUE_EQUIPMENTS ADD CONSTRAINT pk_venue_equipments
  PRIMARY KEY (VENUEID, equipment_num);

/* 16) SCHEDULE_EVENT (add scheduleID FK + event FK) */
ALTER TABLE SCHEDULE_EVENT ADD COLUMN scheduleID VARCHAR(20);

ALTER TABLE SCHEDULE_EVENT ADD CONSTRAINT fk_se_schedule
  FOREIGN KEY (scheduleID) REFERENCES SCHEDULE(scheduleID);

ALTER TABLE SCHEDULE_EVENT ADD CONSTRAINT fk_se_event
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(eventID);

/* 17) EVENT_INVOICES (bridge between EVENT + INVOICES) */
ALTER TABLE EVENT_INVOICES ADD COLUMN eventID VARCHAR(20);

ALTER TABLE EVENT_INVOICES ADD CONSTRAINT fk_ei_event
  FOREIGN KEY (eventID) REFERENCES EVENT(eventID);

ALTER TABLE EVENT_INVOICES ADD CONSTRAINT fk_ei_invoice
  FOREIGN KEY (INVOICEID) REFERENCES INVOICES(invoiceID);

ALTER TABLE EVENT_INVOICES ADD CONSTRAINT pk_event_invoices
  PRIMARY KEY (eventID, INVOICEID);

/* 18) SCHEDULE_PERFORMERS (junction table needs performerID + composite PK) */
ALTER TABLE SCHEDULE_PERFORMERS ADD COLUMN performerID VARCHAR(20);

ALTER TABLE SCHEDULE_PERFORMERS ADD CONSTRAINT fk_sp_schedule
  FOREIGN KEY (SCHEDULEID) REFERENCES SCHEDULE(scheduleID);

ALTER TABLE SCHEDULE_PERFORMERS ADD CONSTRAINT fk_sp_performer
  FOREIGN KEY (performerID) REFERENCES PERFORMERS(performerID);

ALTER TABLE SCHEDULE_PERFORMERS ADD CONSTRAINT pk_schedule_performers
  PRIMARY KEY (SCHEDULEID, performerID);

/* 19) VENDORS_EVENT (needs eventID + composite PK) */
ALTER TABLE VENDORS_EVENT ADD COLUMN eventID VARCHAR(20);

ALTER TABLE VENDORS_EVENT ADD CONSTRAINT fk_ve_vendor
  FOREIGN KEY (VENDORID) REFERENCES VENDOR(vendorID);

ALTER TABLE VENDORS_EVENT ADD CONSTRAINT fk_ve_event
  FOREIGN KEY (eventID) REFERENCES EVENT(eventID);

ALTER TABLE VENDORS_EVENT ADD CONSTRAINT pk_vendors_event
  PRIMARY KEY (VENDORID, eventID);

/* 20) ATTENDEE_EVENT (needs eventID + composite PK) */
ALTER TABLE ATTENDEE_EVENT ADD COLUMN eventID VARCHAR(20);

ALTER TABLE ATTENDEE_EVENT ADD CONSTRAINT fk_ae_attendee
  FOREIGN KEY (ATTENDEE_NAME) REFERENCES ATTENDEES(attendee_name);

ALTER TABLE ATTENDEE_EVENT ADD CONSTRAINT fk_ae_event
  FOREIGN KEY (eventID) REFERENCES EVENT(eventID);

ALTER TABLE ATTENDEE_EVENT ADD CONSTRAINT pk_attendee_event
  PRIMARY KEY (ATTENDEE_NAME, eventID);

/* 21) STAFF_EVENT (needs eventID + composite PK) */
ALTER TABLE STAFF_EVENT ADD COLUMN eventID VARCHAR(20);

ALTER TABLE STAFF_EVENT ADD CONSTRAINT fk_ste_staff
  FOREIGN KEY (STAFFID) REFERENCES STAFF(staffID);

ALTER TABLE STAFF_EVENT ADD CONSTRAINT fk_ste_event
  FOREIGN KEY (eventID) REFERENCES EVENT(eventID);

ALTER TABLE STAFF_EVENT ADD CONSTRAINT pk_staff_event
  PRIMARY KEY (STAFFID, eventID);

/* 22) STAFF_SUPERVISOR (self-reference) */
ALTER TABLE STAFF_SUPERVISOR ADD COLUMN supervisorID VARCHAR(30);

ALTER TABLE STAFF_SUPERVISOR ADD CONSTRAINT fk_ss_staff
  FOREIGN KEY (STAFFID) REFERENCES STAFF(staffID);

ALTER TABLE STAFF_SUPERVISOR ADD CONSTRAINT fk_ss_supervisor
  FOREIGN KEY (supervisorID) REFERENCES STAFF(staffID);

ALTER TABLE STAFF_SUPERVISOR ADD CONSTRAINT pk_staff_supervisor
  PRIMARY KEY (STAFFID, supervisorID);
